name: Tests

on: push
concurrency:
  # Concurrency group that uses the workflow name and PR number if available
  # or commit SHA as a fallback. If a new build is triggered under that
  # concurrency group while a previous build is running it will be canceled.
  # Repeated pushes to a PR will cancel all previous builds, while multiple
  # merges to main will not cancel.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || 
    github.sha }}
  cancel-in-progress: true

env:
  # https://conda.github.io/conda-libmamba-solver/user-guide/configuration/#advanced-options
  CONDA_LIBMAMBA_SOLVER_NO_CHANNELS_FROM_INSTALLED: true

jobs:
  # detect whether any code changes are included in this PR
  changes:
    runs-on: ubuntu-latest
    permissions:
      # necessary to detect changes
      # https://github.com/dorny/paths-filter#supported-workflows
      pull-requests: read
    outputs:
      code: ${{ steps.filter.outputs.code }}
    steps:
    - name: Checkout Source
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8   # v5.0.0
        # dorny/paths-filter needs git clone for non-PR events
        # https://github.com/dorny/paths-filter#supported-workflows
      if: github.event_name != 'pull_request'

    - name: Filter Changes
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36   # v3.0.2
      id: filter
      with:
        filters: |
          code:
            - 'conda/**'
            - 'conda_env/**'
            - 'tests/**'
            - '*.py'
            - 'recipe/**'
            - '.github/workflows/tests.yml'

  # windows test suite
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        # test lower version (w/ defaults) and upper version (w/ defaults and conda-forge)
        python-version: ['3.10', '3.13']
        default-channel: [defaults, conda-forge]
        test-type: [unit, integration]
        test-group: [1, 2, 3]
        exclude:
        - default-channel: conda-forge
          python-version: '3.10'
        - test-type: unit
          test-group: 3
    env:
      ErrorActionPreference: Stop  # powershell exit immediately on error
      PYTEST_MARKER: ${{ matrix.test-type == 'unit' && 'not integration' || 
        'integration' }}
      PYTEST_SPLITS: ${{ matrix.test-type == 'unit' && '2' || '3' }}
      CONDA_TEST_SOLVERS: ${{ github.event_name == 'pull_request' && 'libmamba' 
        || 'libmamba,classic' }}

    steps:
    - name: Checkout Source
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8   # v5.0.0
      with:
        fetch-depth: 0

    - name: Hash + Timestamp
      shell: bash    # use bash to run date command
      run: echo "HASH=${{ runner.os }}-${{ runner.arch }}-Py${{ 
        matrix.python-version }}-${{ matrix.default-channel }}-${{ 
        matrix.test-type }}-${{ matrix.test-group }}-$(date -u "+%Y%m")" >> 
        $GITHUB_ENV

    - name: Cache Conda
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830   # v4.3.0
      with:
          # Use faster GNU tar for all runners
        enableCrossOsArchive: true
        path: D:\conda_pkgs_dir
        key: cache-${{ env.HASH }}

    - name: Setup Miniconda
      uses: 
        conda-incubator/setup-miniconda@835234971496cad1653abb28a638a281cf32541f       # v3.2.0
      with:
        condarc-file: .github\condarc-${{ matrix.default-channel }}
        run-post: false    # skip post cleanup
        pkgs-dirs: D:\conda_pkgs_dir
        installation-dir: D:\conda

    - name: Conda Install
      run: >
        conda install
        --yes
        --file tests\requirements.txt
        --file tests\requirements-${{ runner.os }}.txt
        --file tests\requirements-ci.txt
        --file tests\requirements-s3.txt
        --file tests\requirements-truststore.txt
        python=${{ matrix.python-version }}

    - name: Conda Info
        # view test env info (not base)
      run: python -m conda info --verbose

    - name: Conda Config
      run: conda config --show-sources

    - name: Conda List
      run: conda list --show-channel-urls

    - name: Setup PowerShell
        # for tests/shell, so only necessary for integration tests
      if: matrix.test-type == 'integration'
      run: |
        $PWSH_STABLE = "$env:LOCALAPPDATA\Microsoft\powershell"
        Invoke-Expression "& { $(Invoke-RestMethod https://aka.ms/install-powershell.ps1) } -Destination `"$PWSH_STABLE`""
        $PWSH_PREVIEW = "$env:LOCALAPPDATA\Microsoft\powershell-preview"
        Invoke-Expression "& { $(Invoke-RestMethod https://aka.ms/install-powershell.ps1) } -Preview -Destination `"$PWSH_PREVIEW`""
        "PWSHPATH=$PWSH_STABLE;$PWSH_PREVIEW" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: PowerShell Info
        # for tests/shell, so only necessary for integration tests
      if: matrix.test-type == 'integration'
      run: |
        Get-Command -All powershell
        "$env:PWSHPATH" -split ";" | ForEach-Object { Get-Command -All "$_\pwsh" }

    - name: Run Tests
        # Windows is sensitive to long paths, using `--basetemp=${{ runner.temp }} to
        # keep the test directories shorter
      run: >
        python -m pytest
        --cov=conda
        --basetemp=${{ runner.temp }}
        --durations-path=durations\${{ runner.os }}.json
        --group=${{ matrix.test-group }}
        --splits=${{ env.PYTEST_SPLITS }}
        -m "${{ env.PYTEST_MARKER }}"

  # linux test suite
  linux:
    runs-on: ${{ matrix.runs-on }}
    defaults:
      run:
        # https://github.com/conda-incubator/setup-miniconda#use-a-default-shell
        shell: bash -el {0}  # bash exit immediately on error + login shell
    strategy:
      fail-fast: false
      matrix:
        # test all lower versions (w/ defaults) and upper version (w/ defaults and conda-forge)
        runs-on:
        - ubuntu-latest    # linux-64
        - ubuntu-24.04-arm    # linux-aarch64
        python-version: ['3.10', '3.11', '3.12', '3.13']
        default-channel: [defaults, conda-forge]
        test-type: [unit, integration]
        test-group: [1, 2, 3]
        exclude:
        - python-version: '3.10'
          default-channel: conda-forge
        - python-version: '3.11'
          default-channel: conda-forge
        - python-version: '3.12'
          default-channel: conda-forge
        - test-type: unit
          test-group: 3
        - runs-on: ubuntu-24.04-arm
          python-version: '3.10'
        - runs-on: ubuntu-24.04-arm
          python-version: '3.11'
        - runs-on: ubuntu-24.04-arm
          python-version: '3.12'
    env:
      PYTEST_MARKER: ${{ matrix.test-type == 'unit' && 'not integration' || 
        'integration' }}
      PYTEST_SPLITS: ${{ matrix.test-type == 'unit' && '2' || '3' }}
      CONDA_TEST_SOLVERS: ${{ github.event_name == 'pull_request' && ( 
        matrix.python-version != '3.13' || matrix.default-channel == 
        'conda-forge' ) && 'libmamba' || 'libmamba,classic' }}

    steps:
    - name: Checkout Source
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8   # v5.0.0
      with:
        fetch-depth: 0

    - name: Hash + Timestamp
      run: echo "HASH=${{ runner.os }}-${{ runner.arch }}-Py${{ 
        matrix.python-version }}-${{ matrix.default-channel }}-${{ 
        matrix.test-type }}-${{ matrix.test-group }}-$(date -u "+%Y%m")" >> 
        $GITHUB_ENV

    - name: Cache Conda
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830   # v4.3.0
      with:
        path: ~/conda_pkgs_dir
        key: cache-${{ env.HASH }}

    - name: Setup Miniconda
      uses: 
        conda-incubator/setup-miniconda@835234971496cad1653abb28a638a281cf32541f       # v3.2.0
      with:
        condarc-file: .github/condarc-${{ matrix.default-channel }}
        run-post: false    # skip post cleanup
        miniconda-version: ${{ matrix.default-channel == 'defaults' && 'latest' 
          || null }}
        miniforge-version: ${{ matrix.default-channel == 'conda-forge' && 
          'latest' || null }}

    - name: Conda Install
      run: >
        conda install
        --yes
        --file tests/requirements.txt
        --file tests/requirements-${{ runner.os }}.txt
        --file tests/requirements-ci.txt
        --file tests/requirements-s3.txt
        --file tests/requirements-truststore.txt
        python=${{ matrix.python-version }}

    - name: Conda Info
        # view test env info (not base)
      run: python -m conda info --verbose

    - name: Conda Config
      run: conda config --show-sources

    - name: Conda List
      run: conda list --show-channel-urls

    - name: Setup Shells
        # for tests/shell, so only necessary for integration tests
      if: matrix.test-type == 'integration'
      run: sudo apt update && sudo apt install ash csh fish tcsh xonsh zsh

    - name: Run Tests
      run: >
        python -m pytest
        --cov=conda
        --durations-path=durations/${{ runner.os }}.json
        --group=${{ matrix.test-group }}
        --splits=${{ env.PYTEST_SPLITS }}
        -m "${{ env.PYTEST_MARKER }}"

  # linux typing
  linux-typing:
    # only run test suite if there are code changes
    needs: changes
    if: needs.changes.outputs.code == 'true'

    runs-on: ubuntu-22.04
    defaults:
      run:
        # https://github.com/conda-incubator/setup-miniconda#use-a-default-shell
        shell: bash -el {0}  # bash exit immediately on error + login shell
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.13']

    steps:
    - name: Checkout Source
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8   # v5.0.0
      with:
        fetch-depth: 0

    - name: Hash + Timestamp
      run: echo "HASH=${{ runner.os }}-${{ runner.arch }}-Py${{ 
        matrix.python-version }}-benchmark-$(date -u "+%Y%m")" >> $GITHUB_ENV

    - name: Cache Conda
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830   # v4.3.0
      with:
        path: ~/conda_pkgs_dir
        key: cache-${{ env.HASH }}

    - name: Setup Miniconda
      uses: 
        conda-incubator/setup-miniconda@835234971496cad1653abb28a638a281cf32541f       # v3.2.0
      with:
        condarc-file: .github/condarc-defaults
        run-post: false    # skip post cleanup

    - name: Conda Install
      run: >
        conda install
        --yes
        --file tests/requirements.txt
        --file tests/requirements-${{ runner.os }}.txt
        --file tests/requirements-ci.txt
        --file tests/requirements-s3.txt
        --file tests/requirements-typing.txt
        --file tests/requirements-truststore.txt
        python=${{ matrix.python-version }}

    - name: Conda Info
        # view test env info (not base)
      run: python -m conda info --verbose

    - name: Conda Config
      run: conda config --show-sources

    - name: Conda List
      run: conda list --show-channel-urls

    - name: Run mypy
      run: >
        mypy
        --cobertura-xml-report=.mypy_cache/coverage.xml
        --txt-report=.mypy_cache/report.txt
        --html-report=.mypy_cache/report.html
        || true
